### PR TITLE
Fix _exe_cmd in installer.py

### PR DESCRIPTION
**Pull request by sharkwouter**
## Description

This is a small change building on your ideas which makes the code a bit cleaner and keeps the separation between stderr and stdout. Hope this helps! I really appreciate you finding this specific issue and doing the initial code for this

## Checklist
 
 - [ ] _CHANGELOG.md_ was updated (**format**: - Change made (thanks to github_username))

### CODE REVIEW

**Review by GB609 — COMMENTED** [review]
~~This certainly is an improvement in that minigalaxy does not freeze up and there is no blocking readline anymore.~~

Edit: I'm sorry, we can't use read. Because read() goes on until EOF is reached.
popen
popen-buffer
read

This is the very reason why i changed from communicate() to readline() to read in partial steps.

I also had another idea related to that entire input reading business just now.
In the initial code i just tried to keep what was done before which is that minigalaxy captures the stdout and stderr. 
But stdout actually wasn't really used before.
What do you think about a little change of concept here? We could just let the opened process write its stdout without piping it through python and only capture stderr.
That means, we could use stdout=NONE and stderr=PIPE.

**Comment by sharkwouter** [comment]
This is a hard problem. I'll look into this some more. It is possible to tell read to get a specific amount of characters, but it would still wait for at least that amount of characters to appear. So I don't think that is a solution either.

**Comment by GB609** [comment]
> This is a hard problem. I'll look into this some more. It is possible to tell read to get a specific amount of characters, but it would still wait for at least that amount of characters to appear. So I don't think that is a solution either.

Well, accoding to the docs, the Stream also can be operated in 'non-blocking mode' where read returns when there isn't more to read. But i havent found how to get this in through POpen.
The wait for a certain amount if characters shouldnt be too problematic while the process runs when the amount is sufficiently small. And from what i could see, when there's an EOF before the read buffer is filled it throws some io error. So partial output and returning can be covered.

Isnt there a way to 'look ahead' in a none-blocking way in a buffer? In that case we could check if theres a newline and read this line in the respective stream, otherwise just skip that stream until the next iteration.

**Comment by sharkwouter** [comment]
That is great, good job. I'll apply it.

**Comment by sharkwouter** [comment]
Okay, I've updated it now.

**Pull request merged**
